apiVersion: batch/v1
kind: Job
metadata:
  name: postZahtev
spec:
  template:
    spec:
      containers:
      - name: postZahtev
        image: branko98/client:0.1
        command: ["python", "postRequest.py"]
      restartPolicy: OnFailure